# Generated by Django 2.1.4 on 2018-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image_url',
            field=models.URLField(),
        ),
    ]
